# Generated by Django 4.2 on 2024-03-23 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Service name')),
                ('logo', models.ImageField(upload_to='services/images/', verbose_name='Logo image')),
                ('description', models.TextField(verbose_name='Description')),
                ('usage_policy', models.TextField(verbose_name='Usage Policy')),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tariff name')),
                ('description', models.TextField(verbose_name='Description')),
                ('duration', models.DurationField(verbose_name='Duration')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('test_period', models.DurationField(blank=True, null=True, verbose_name='Test period')),
                ('test_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Test price')),
                ('cashback', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сashback amount')),
                ('cashback_conditions', models.TextField(verbose_name='Cashback conditions')),
                ('is_direct', models.BooleanField(default=True, verbose_name='Direct subscription')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Transaction date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transaction amount')),
                ('payment_status', models.PositiveSmallIntegerField(choices=[(0, 'Отказано'), (1, 'Зачислено'), (2, 'Ожидается')], default=2, verbose_name='Payment Status')),
            ],
        ),
        migrations.CreateModel(
            name='UserTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active subscription')),
                ('auto_renewal', models.BooleanField(default=True, verbose_name='Auto renewal tariff')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariffs', to='services.tariff', verbose_name='Tariff')),
            ],
        ),
    ]
