# Generated by Django 4.2 on 2024-03-24 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'verbose_name': 'Подписка', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='tariff',
            options={'verbose_name': 'Тариф', 'verbose_name_plural': 'Тарифы'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='usertariff',
            options={'verbose_name': 'Тариф пользователя', 'verbose_name_plural': 'Тарифы пользователя'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='logo',
            field=models.ImageField(upload_to='services/images/', verbose_name='Логотив'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название сервиса'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='usage_policy',
            field=models.TextField(verbose_name='Политика использования'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='cashback',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Кешбэк'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='cashback_conditions',
            field=models.TextField(verbose_name='Условия начисления кешбэка'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='duration',
            field=models.DurationField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название тарифа'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='services.subscription', verbose_name='Подписка'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='test_period',
            field=models.DurationField(blank=True, null=True, verbose_name='Пробный период'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='test_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для пробного периода'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Отказано'), (1, 'Зачислено'), (2, 'Ожидается')], default=2, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.usertariff', verbose_name='Тариф пользователя'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная/неактивная подписка'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='tariff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariffs', to='services.tariff', verbose_name='Тариф'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariffs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
