# Generated by Django 4.2 on 2024-03-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_subscription_options_alter_tariff_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='logo',
            field=models.ImageField(upload_to='services/images/', verbose_name='Логотип'),
        ),
    ]
