# Generated by Django 4.2 on 2024-03-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_subscription_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='services/images/', verbose_name='Логотип'),
        ),
    ]
