# Generated by Django 4.2 on 2024-03-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_subscription_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='is_direct',
            field=models.BooleanField(default=True, verbose_name='Прямая подписка'),
        ),
    ]
