# Generated by Django 4.2 on 2024-03-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_tariff_is_direct_usertariff_is_direct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertariff',
            name='auto_renewal',
            field=models.BooleanField(default=True, verbose_name='Aвтопродление'),
        ),
    ]
