# Generated by Django 4.2 on 2024-03-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_usertariff_auto_renewal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertariff',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='is_direct',
            field=models.BooleanField(default=False, verbose_name='Прямая подписка'),
        ),
    ]
