# Generated by Django 4.2 on 2024-03-28 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_remove_usertariff_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='duration',
        ),
        migrations.AddField(
            model_name='tariff',
            name='period',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], default=1, verbose_name='Срок'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tariff',
            name='test_period',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], null=True, verbose_name='Пробный период'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='usertariff',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала'),
        ),
    ]
