# Generated by Django 4.2 on 2024-03-29 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_tariff_duration_tariff_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='usage_policy',
        ),
        migrations.AddField(
            model_name='subscription',
            name='partner_rules',
            field=models.TextField(default='...', verbose_name='Правила партнера'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='personal_data_policy',
            field=models.TextField(default='...', verbose_name='Политика обработки ПД'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Отказано'), (1, 'Зачислено')], default=0, verbose_name='Статус оплаты'),
        ),
    ]
