# Generated by Django 4.2 on 2024-03-31 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_subscription_usage_policy_and_more'),
        ('services', '0012_transaction_user'),
    ]

    operations = [
    ]
