# Generated by Django 4.2 on 2024-03-31 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_merge_20240331_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertariff',
            name='promo_code',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Промокод'),
        ),
        migrations.AddField(
            model_name='usertariff',
            name='promo_code_period',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения промокода'),
        ),
    ]
