# Generated by Django 4.2 on 2024-03-31 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_usertariff_promo_code_usertariff_promo_code_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertariff',
            name='promo_code',
            field=models.CharField(default=0, max_length=13, unique=True, verbose_name='Промокод'),
            preserve_default=False,
        ),
    ]
