# Generated by Django 4.2 on 2024-04-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_usertariff_promo_code_usertariff_promo_code_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
