# Generated by Django 4.2 on 2024-03-31 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='father_name',
            field=models.CharField(default='Иванович', help_text='Введите отчетство пользователя', max_length=254, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='Иван', help_text='Введите имя пользователя', max_length=254, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='Иванов', help_text='Введите фамилию пользователя', max_length=254, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='+7 (111) 111-11-11', help_text='Введите номер телефона в формате +7 (111) 111-11-11', max_length=50, verbose_name='Номер телефона'),
        ),
    ]
